# Generated by Django 4.2.9 on 2024-01-24 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
                ('text_field', models.TextField()),
                ('integer_field', models.IntegerField()),
                ('float_field', models.FloatField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boolean_field', models.BooleanField()),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='uploads/')),
                ('image_field', models.ImageField(upload_to='images/')),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
                ('choice_field', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B')], max_length=2)),
                ('slug_field', models.SlugField()),
                ('binary_field', models.BinaryField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('duration_field', models.DurationField()),
                ('ip_address_field', models.GenericIPAddressField(protocol='IPv4')),
                ('json_field', models.JSONField()),
                ('validated_field', models.IntegerField()),
                ('foreign_key_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examplemodel_foreign_keys', to=settings.AUTH_USER_MODEL)),
                ('many_to_many_field', models.ManyToManyField(related_name='examplemodel_many_to_manys', to=settings.AUTH_USER_MODEL)),
                ('one_to_one_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examplemodel_one_to_ones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
